# cryptlib GNUmakefile
#
# This GNUmakefile executes the stock cryptlib makefile to produce
# a library for inclusion in qodem.
#
# ----
#
# See the COPYING file in this directory for the cryptlib licensing
# terms.
#
# ----
#
# qodem itself, and this specific GNUmakefile, are dedicated to the
# public domain.
#
# Written 2003-2017 by Kevin Lamonte
#
# To the extent possible under law, the author(s) have dedicated all
# copyright and related and neighboring rights to this software to the
# public domain worldwide. This software is distributed without any
# warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication
# along with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

all: default

default: libcl.a

libcl.a:
	-make -f makefile

distclean: clean

clean:
	-make -f makefile clean

dist:

distdir:

install:
