.TH xqodem 1 "April 27, 2017"
.SH NAME
xqodem \- Qodem Terminal Emulator
.SH SYNOPSIS
.B xqodem
.I qodem-options
.SH DESCRIPTION
.B xqodem
is a script wrapper around
.B qodem.
It tries to find a UTF\-8 and color capable X11-based terminal on your
system, and then runs qodem in a terminal session.
.SH OPTIONS
See
.I qodem
(1).
.SH PUBLIC DOMAIN NOTICE
Written 2003\-2017 by Kevin Lamonte
.PP
To the extent possible under law, the author(s) have dedicated all
copyright and related and neighboring rights to this software to the
public domain worldwide. This software is distributed without any
warranty.
.SH "SEE ALSO"
qodem(1)
